# Generated by Django 5.1.1 on 2024-09-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('short_description', models.CharField(blank=True, max_length=2000)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
