# Generated by Django 5.1.1 on 2024-12-19 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Itemsapp', '0003_request_selecteditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_spacial', models.TextField(blank=True)),
                ('description_spacial', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_details', to='Itemsapp.request')),
            ],
        ),
    ]
