# Generated by Django 5.1.1 on 2024-12-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Itemsapp', '0005_alter_requestdetail_detail_spacial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdetail',
            name='detail_spacial',
            field=models.TextField(blank=True, verbose_name='Add Item '),
        ),
    ]
