# Generated by Django 5.1.1 on 2025-01-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Itemsapp', '0006_alter_requestdetail_detail_spacial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='details',
            field=models.TextField(blank=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Ship Name'),
        ),
    ]
